services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi_hw
    # volumes:
    #   - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5431:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - pg-network

  # run once to ingest data
  taxi_ingest:
    build: .
    image: taxi_ingest:hw
    command: 
      - --user=root 
      - --password=root
      - --host=pgdatabase
      - --port=5432
      - --db=ny_taxi_hw
      - --table_name=green_taxi_trips
      - --url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-09.csv.gz
    depends_on:
      - pgdatabase      
      - pgadmin
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge
    name: pg-network